# docker-compose -f .\docker-compose.yml up
version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: trades-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: trades-rabbit
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  sql_data: